stages:
  - build
  - deploy

build-docker:
  stage: build
  image: docker:stable
  only:
    - main
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab+deploy-token-1 -p "${ACCESS_TOKEN}" registry.brist.loc
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" --build-arg branch="${CI_COMMIT_REF_NAME}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh
  script:
    - ssh dev@172.16.10.22 "docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} && docker run -d --name my-container ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"

