stages:
  - build
  - deploy

build-docker:
  stage: build
  image: docker:stable
  only:
    - main
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab+deploy-token-1 -p "${ACCESS_TOKEN}" registry.brist.loc
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" --build-arg branch="${CI_COMMIT_REF_NAME}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s) # Start the SSH agent
    - echo "$ID_RSA" | ssh-add - # Add the private key
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 172.16.10.22 >> ~/.ssh/known_hosts
  script:
    - ssh dev@172.16.10.22 "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY && docker pull $TAG_COMMIT && docker container rm -f my-app || true && docker run -d -p 80:80 -p 3000:3000 --name my-app $TAG_COMMIT"




